- name: docker build and push image
  gather_facts: true
  hosts: all
  become: yes
  vars:
    project_dest: "/home/ds-bootcamp/"
    repo_url: "https://github.com/slavlotski/Tomorrow-s-analysts-ds-bootcamp.git"
    repo_branch: "main"
  tasks:
    - name: Get all secrets from Github
      set_fact:
        docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        docker_token: "{{ lookup('env', 'DOCKER_TOKEN') }}"
        dockerhub_reponame: "{{ lookup('env', 'DOCKERHUB_REPONAME') }}"
        telegram_bot_token: "{{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}"
        openai_api_key: "{{ lookup('env', 'OPENAI_API_KEY') }}"

    - name: Create destination directory if it does not exist
      file:
        path: "{{ project_dest }}"
        state: directory
        mode: '0755'

    - name: Clone GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dest }}"
        version: "{{ repo_branch }}"

    - name: Log in to Docker hub
      docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"

    - name: Build the Docker image
      docker_image:
        build:
          path: "{{ project_dest }}."
          args:
            TELEGRAM_BOT_TOKEN: "{{ telegram_bot_token }}"
            OPENAI_API_KEY: "{{ openai_api_key }}"
        name: "{{ docker_username }}/{{ dockerhub_reponame }}"
        tag: "latest"
        source: build
        push: no