- name: docker build and push image
  gather_facts: true
  hosts: all
  become: yes
  vars:
    repo_url: "https://raw.githubusercontent.com/slavlotski/Tomorrow-s-analysts-ds-bootcamp/main"
    project_dest: "/home/ds-bootcamp"
  tasks:
    - name: Get all secrets from Github
      set_fact:
        docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        docker_token: "{{ lookup('env', 'DOCKER_TOKEN') }}"
        dockerhub_reponame: "{{ lookup('env', 'DOCKERHUB_REPONAME') }}"
        telegram_bot_token: "{{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}"
        openai_api_key: "{{ lookup('env', 'OPENAI_API_KEY') }}"

    - name: Create destination directory if it does not exist
      file:
        path: "{{ project_dest }}"
        state: directory
        mode: '0755'

    - name: Copy specific directories or files to the destination
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: "{{ repo_url }}/config", dest: "{{ project_dest }}/config" }
        - { src: "{{ repo_url }}/handlers", dest: "{{ project_dest }}/handlers" }
        - { src: "{{ repo_url }}/utils", dest: "{{ project_dest }}/utils" }
        - { src: "{{ repo_url }}/app.py", dest: "{{ project_dest }}/app.py" }
        - { src: "{{ repo_url }}/requirements.txt", dest: "{{ project_dest }}/requirements.txt" }
        - { src: "{{ repo_url }}/Dockerfile", dest: "{{ project_dest }}/Dockerfile" }


    - name: Log in to Docker hub
      docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"

    - name: Build the Docker image
      docker_image:
        build:
          path: "{{ project_dest }}"
          buildargs:
            TELEGRAM_BOT_TOKEN: "{{ telegram_bot_token }}"
            OPENAI_API_KEY: "{{ openai_api_key }}"
        name: "{{ docker_username }}/{{ dockerhub_reponame }}"
        tag: "latest"
        push: no