- name: ds-bootcamp
  gather_facts: false
  hosts: all
  become: yes
  vars:
    packages:
      - vim
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - build-essential
      - python3
      - git
  tasks:
    - name: Ensure common packages are installed on Debian-based systems
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_os_family == "Ubuntu"

    - name: Get all secrets from Github
      set_fact:
        docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        docker_token: "{{ lookup('env', 'DOCKER_TOKEN') }}"

    - name: Log in to Docker hub
      docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"
