name: Deploy virtual assitant to remote server
on:
  push:
    branches:
      - main
jobs:
  install-packages-to-remote-server:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Virtual Assistant to Remote server
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./ansible/install-packages.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: ./ansible/inventory.ini
        options: |
          --verbose

  docker-build-push-stage:
    runs-on: ubuntu-latest
    needs: install-packages-to-remote-server
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Virtual Assistant to Remote server
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./ansible/docker-build-pull.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: ./ansible/inventory.ini
        options: |
          --verbose
